### ISSUE TITLE
List of mobile issues

### ISSUE THREAD

**Issue by RobertRR11** [Compliance-Resource-Pack/App#24]
- [x] theme color not consistent with header
![image](https://user-images.githubusercontent.com/57044042/150793206-f31ec736-d2c7-4530-bf28-6da168c57d7e.jpeg)

- [x] background image scaled very big on long lists
![image](https://user-images.githubusercontent.com/57044042/150793364-993ed723-d1b3-4d4d-a888-fe15d735a3ef.png)

- [x] menu is infinitely long / as long as the page
![image](https://user-images.githubusercontent.com/57044042/150793473-1855486b-725f-42e4-b362-18d88bb06391.png)

- [x] every path overflows
![image](https://user-images.githubusercontent.com/57044042/150793669-2bbead7e-957c-4076-a675-4b021d7dc075.png)

**Comment by TheRolfFR** [comment]
There is no theme-color tag so it's not going to work,
what you see is the background image. You can add one if you want.

I have no problem with the background image as it uses the rule ``background-attachment: fixed`` in order to scale it at the size of the screen. I replicated with the same content but got a correct background. Could you give me details on the browser and OS used ?

I fixed the menu with 65777fee6e48c64c23f739d91dcb43ec4e6ecc0f with the ``fixed`` property instead of ``absolute``

The paths are always breaking, we should consider [word-break](https://developer.mozilla.org/en-US/docs/Web/CSS/word-break) css rule or ``overflow-x: auto`` for the container

**Comment by TheRolfFR** [comment]
Looks like there is a bug with this property on your device, as shown on https://caniuse.com/background-attachment:
![image](https://user-images.githubusercontent.com/18086786/151385576-195ade86-b117-4f8d-b08c-7ccc287b9f59.png)

**Comment by TheRolfFR** [comment]
Theme color fixed in 6539e0db8557d6cee37e9fdbc28fb7bf0d183b78
Background image: will not be fixed
texture path length fixed in 75fa404e0e403d1a8607c60992bd7a06e90a64cf
